import type { Game, Stat, Pillar, NavLink } from '@/types'

export const NAV_LINKS: NavLink[] = [
  { label: 'Games',   href: '/games' },
  { label: 'Studio',  href: '/#about' },
  { label: 'Vision',  href: '/#pillars' },
  { label: 'Careers', href: '/careers' },
]

export const STATS: Stat[] = [
  { value: 12,  label: 'Games Released' },
  { value: 4,   suffix: 'M+', label: 'Players Worldwide' },
  { value: 28,  label: 'Studio Members' },
  { value: 6,   label: 'Industry Awards' },
]

export const GAMES: Game[] = [
  {
    id: '1',
    slug: 'pandemic-lost-haven',
    title: 'Pandemic:',
    subtitle: 'The Lost Haven',
    description: 'A brutal, realistic zombie survival experience for mobile. Inspired by the classics, reimagined with RTX-level graphics.',
    longDescription: `An RTX-level zombie survival game bringing console-quality horror to mobile devices. Inspired by genre-defining classics like The Last of Us and Resident Evil, Pandemic: The Lost Haven pushes mobile hardware to its absolute limit to deliver a truly terrifying, atmospheric experience.`,
    genre: 'Survival Horror',
    year: 2024,
    status: 'released',
    imageSrc: '/games/pandemic-lost-haven/hero.jpg',
    videoSrc: '/games/pandemic-lost-haven/pandemic_trailer.mp4',
    accentColor: '#ff4500',
    bgGradient: `radial-gradient(ellipse at 50% 80%, rgba(255,69,0,0.4) 0%, transparent 60%), linear-gradient(135deg, #0a0002 0%, #1a0808 50%, #0d0505 100%)`,
    tags: ['Survival', 'Zombies', 'Horror'],
    platforms: ['Android'],
    pcAvailable: false,
    androidAvailable: true,
    iosAvailable: false,
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.draculegames.zombiepandemic',
    rating: 9.2,
    downloads: '100K+',
    features: [
      'Console-quality RTX graphics on mobile',
      'Intense, resource-scarce survival gameplay',
      'Terrifying enemy AI and infection mechanics',
    ],
  },
  {
    id: '2',
    slug: 'rail-runner-rtx',
    title: 'Rail Runner',
    subtitle: 'RTX',
    description: 'An endless runner pushing mobile graphics to the bleeding edge. High-octane action with realistic rendering.',
    longDescription: `An exhilarating endless runner experience boasting RTX-level realistic graphics for mobile devices. Taking inspiration from Subway Surfers but elevating it with hyper-realistic visuals, dynamic lighting, and heart-pounding action.`,
    genre: 'Action Runner',
    year: 2024,
    status: 'released',
    imageSrc: '/games/rail-runner-rtx/hero.jpg', 
    videoSrc: '/games/rail-runner-rtx/rail_trailer.mp4',
    accentColor: '#00f5ff',
    bgGradient: `radial-gradient(ellipse at 60% 40%, rgba(0,245,255,0.4) 0%, transparent 60%), linear-gradient(135deg, #00050a 0%, #050818 50%, #020a10 100%)`,
    tags: ['Runner', 'Action', 'Arcade'],
    platforms: ['Android'],
    pcAvailable: false,
    androidAvailable: true,
    iosAvailable: false,
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.draculegames.railrunnerrtx',
    rating: 8.8,
    downloads: '50K+',
    features: [
      'Next-generation realism in a mobile runner',
      'Dynamic weather and lighting effects',
      'Fast-paced parkour and obstacle dodging',
    ],
  },
  {
    id: '3',
    slug: 'ember-throne',
    title: 'Ember',
    subtitle: 'Throne',
    description: 'Coming Soon: Rule the shattered kingdoms or burn them to ash.',
    longDescription: `Currently in development for PC and Consoles. Ember Throne is an upcoming 60+ hour open-world Action RPG where every faction, ally, and enemy remembers your choices.`,
    genre: 'Action RPG',
    year: 2025,
    status: 'upcoming',
    imageSrc: '/games/ember-throne/hero.jpg',
    videoSrc: '/games/ember-throne/trailer.mp4',
    accentColor: '#ffaa00',
    bgGradient: `radial-gradient(ellipse at 30% 70%, rgba(255,170,0,0.6) 0%, transparent 60%), linear-gradient(135deg, #0a0500 0%, #1a0a00 50%, #0d0500 100%)`,
    tags: ['Open World', 'RPG'],
    platforms: ['PC'],
    pcAvailable: false,
    androidAvailable: false,
    iosAvailable: false,
    rating: 0,
    features: ['Branching narrative', 'Dynamic factions', 'Deep combat'],
  },
  {
    id: '4',
    slug: 'void-protocol',
    title: 'Void',
    subtitle: 'Protocol',
    description: 'Coming Soon: Navigate a dying space station where every system has turned against you.',
    longDescription: `Currently in development. Void Protocol is an upcoming sci-fi survival horror FPS where the station's AI has gone rogue.`,
    genre: 'Sci-Fi FPS',
    year: 2026,
    status: 'upcoming',
    imageSrc: '/games/void-protocol/hero.jpg',
    videoSrc: '/games/void-protocol/trailer.mp4',
    accentColor: '#a855f7',
    bgGradient: `radial-gradient(ellipse at 70% 60%, rgba(168,85,247,0.5) 0%, transparent 60%), linear-gradient(135deg, #05000a 0%, #0a001a 50%, #050010 100%)`,
    tags: ['Survival', 'Horror'],
    platforms: ['Xbox', 'PlayStation'],
    pcAvailable: false,
    androidAvailable: false,
    iosAvailable: false,
    rating: 0,
    features: ['Zero-G combat', 'Rogue AI', 'Permadeath mode'],
  },
  {
    id: '5',
    slug: 'iron-citadel',
    title: 'Iron',
    subtitle: 'Citadel',
    description: 'Coming Soon: Build your fortress. Defend your realm. Crush every siege.',
    longDescription: `Currently in early development. An upcoming RTS experience bringing deep tactical gameplay to all platforms.`,
    genre: 'Strategy RTS',
    year: 2026,
    status: 'upcoming',
    imageSrc: '/games/iron-citadel/hero.jpg',
    videoSrc: '/games/iron-citadel/trailer.mp4',
    accentColor: '#ff0055',
    bgGradient: `radial-gradient(ellipse at 40% 60%, rgba(255,0,85,0.4) 0%, transparent 60%), linear-gradient(135deg, #0a0005 0%, #1a000a 50%, #0a0005 100%)`,
    tags: ['Strategy', 'RTS'],
    platforms: ['PC', 'Android', 'iOS'],
    pcAvailable: false,
    androidAvailable: false,
    iosAvailable: false,
    rating: 0,
    features: ['Multiplayer siege', '100+ missions', 'Cross-platform'],
  },
]

export const PILLARS: Pillar[] = [
  { icon: '⬡', title: 'World Building', description: 'Every game is a universe — with history, culture, and secrets buried in every pixel.' },
  { icon: '◈', title: 'Player Agency', description: 'Your choices have weight. Our worlds bend and break around the decisions you make.' },
  { icon: '◎', title: 'Visual Mastery', description: 'From concept to launch, we push every frame to the bleeding edge of possibility.' },
  { icon: '⬟', title: 'Sonic Identity', description: "Adaptive soundscapes that react to you — the music tells your story, not the script's." },
]

export const TECH_ITEMS = [
  'Next.js 14', 'Unreal Engine 5', 'React Three Fiber', 'GSAP ScrollTrigger',
  'WebGL Shaders', 'Stripe Payments', 'PostgreSQL', 'Prisma ORM',
  'Vercel Edge', 'Zustand State', 'Framer Motion', 'TypeScript', 'Tailwind CSS', 'Clerk Auth',
]

export const HEX_SKILLS = [
  'UI/UX', '3D Art', 'VFX', 'Sound',
  'Lore', 'Code', 'AI', 'Design',
  'SFX', 'QA', 'Network', 'Render',
  'Physics', 'Story', 'Maps', 'Engine',
]
